// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/test.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Test1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id1           string                 `protobuf:"bytes,10,opt,name=id1,proto3" json:"id1,omitempty"`
	Name1         string                 `protobuf:"bytes,20,opt,name=name1,proto3" json:"name1,omitempty"`
	Age1          int32                  `protobuf:"varint,30,opt,name=age1,proto3" json:"age1,omitempty"`
	Email1        string                 `protobuf:"bytes,40,opt,name=email1,proto3" json:"email1,omitempty"`
	Address1      string                 `protobuf:"bytes,50,opt,name=address1,proto3" json:"address1,omitempty"`
	Pincode1      int32                  `protobuf:"varint,60,opt,name=pincode1,proto3" json:"pincode1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Test1) Reset() {
	*x = Test1{}
	mi := &file_proto_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Test1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test1) ProtoMessage() {}

func (x *Test1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test1.ProtoReflect.Descriptor instead.
func (*Test1) Descriptor() ([]byte, []int) {
	return file_proto_test_proto_rawDescGZIP(), []int{0}
}

func (x *Test1) GetId1() string {
	if x != nil {
		return x.Id1
	}
	return ""
}

func (x *Test1) GetName1() string {
	if x != nil {
		return x.Name1
	}
	return ""
}

func (x *Test1) GetAge1() int32 {
	if x != nil {
		return x.Age1
	}
	return 0
}

func (x *Test1) GetEmail1() string {
	if x != nil {
		return x.Email1
	}
	return ""
}

func (x *Test1) GetAddress1() string {
	if x != nil {
		return x.Address1
	}
	return ""
}

func (x *Test1) GetPincode1() int32 {
	if x != nil {
		return x.Pincode1
	}
	return 0
}

type CreateTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Test          *Test1                 `protobuf:"bytes,10,opt,name=test,proto3" json:"test,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTestRequest) Reset() {
	*x = CreateTestRequest{}
	mi := &file_proto_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTestRequest) ProtoMessage() {}

func (x *CreateTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTestRequest.ProtoReflect.Descriptor instead.
func (*CreateTestRequest) Descriptor() ([]byte, []int) {
	return file_proto_test_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTestRequest) GetTest() *Test1 {
	if x != nil {
		return x.Test
	}
	return nil
}

type UpdateTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id1           string                 `protobuf:"bytes,10,opt,name=id1,proto3" json:"id1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTestRequest) Reset() {
	*x = UpdateTestRequest{}
	mi := &file_proto_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTestRequest) ProtoMessage() {}

func (x *UpdateTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTestRequest.ProtoReflect.Descriptor instead.
func (*UpdateTestRequest) Descriptor() ([]byte, []int) {
	return file_proto_test_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTestRequest) GetId1() string {
	if x != nil {
		return x.Id1
	}
	return ""
}

type CreateTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,10,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTestResponse) Reset() {
	*x = CreateTestResponse{}
	mi := &file_proto_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTestResponse) ProtoMessage() {}

func (x *CreateTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTestResponse.ProtoReflect.Descriptor instead.
func (*CreateTestResponse) Descriptor() ([]byte, []int) {
	return file_proto_test_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Test          *Test1                 `protobuf:"bytes,10,opt,name=test,proto3" json:"test,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTestResponse) Reset() {
	*x = UpdateTestResponse{}
	mi := &file_proto_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTestResponse) ProtoMessage() {}

func (x *UpdateTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTestResponse.ProtoReflect.Descriptor instead.
func (*UpdateTestResponse) Descriptor() ([]byte, []int) {
	return file_proto_test_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTestResponse) GetTest() *Test1 {
	if x != nil {
		return x.Test
	}
	return nil
}

var File_proto_test_proto protoreflect.FileDescriptor

const file_proto_test_proto_rawDesc = "" +
	"\n" +
	"\x10proto/test.proto\x12\x06testpb\"\x93\x01\n" +
	"\x05Test1\x12\x10\n" +
	"\x03id1\x18\n" +
	" \x01(\tR\x03id1\x12\x14\n" +
	"\x05name1\x18\x14 \x01(\tR\x05name1\x12\x12\n" +
	"\x04age1\x18\x1e \x01(\x05R\x04age1\x12\x16\n" +
	"\x06email1\x18( \x01(\tR\x06email1\x12\x1a\n" +
	"\baddress1\x182 \x01(\tR\baddress1\x12\x1a\n" +
	"\bpincode1\x18< \x01(\x05R\bpincode1\"6\n" +
	"\x11CreateTestRequest\x12!\n" +
	"\x04test\x18\n" +
	" \x01(\v2\r.testpb.Test1R\x04test\"%\n" +
	"\x11UpdateTestRequest\x12\x10\n" +
	"\x03id1\x18\n" +
	" \x01(\tR\x03id1\".\n" +
	"\x12CreateTestResponse\x12\x18\n" +
	"\amessage\x18\n" +
	" \x01(\tR\amessage\"7\n" +
	"\x12UpdateTestResponse\x12!\n" +
	"\x04test\x18\n" +
	" \x01(\v2\r.testpb.Test1R\x04test2\x97\x01\n" +
	"\vTestService\x12C\n" +
	"\n" +
	"CreateTest\x12\x19.testpb.CreateTestRequest\x1a\x1a.testpb.CreateTestResponse\x12C\n" +
	"\n" +
	"UpdateTest\x12\x19.testpb.UpdateTestRequest\x1a\x1a.testpb.UpdateTestResponseB\x1cZ\x1atest-grpc-gin/proto/testpbb\x06proto3"

var (
	file_proto_test_proto_rawDescOnce sync.Once
	file_proto_test_proto_rawDescData []byte
)

func file_proto_test_proto_rawDescGZIP() []byte {
	file_proto_test_proto_rawDescOnce.Do(func() {
		file_proto_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_test_proto_rawDesc), len(file_proto_test_proto_rawDesc)))
	})
	return file_proto_test_proto_rawDescData
}

var file_proto_test_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_test_proto_goTypes = []any{
	(*Test1)(nil),              // 0: testpb.Test1
	(*CreateTestRequest)(nil),  // 1: testpb.CreateTestRequest
	(*UpdateTestRequest)(nil),  // 2: testpb.UpdateTestRequest
	(*CreateTestResponse)(nil), // 3: testpb.CreateTestResponse
	(*UpdateTestResponse)(nil), // 4: testpb.UpdateTestResponse
}
var file_proto_test_proto_depIdxs = []int32{
	0, // 0: testpb.CreateTestRequest.test:type_name -> testpb.Test1
	0, // 1: testpb.UpdateTestResponse.test:type_name -> testpb.Test1
	1, // 2: testpb.TestService.CreateTest:input_type -> testpb.CreateTestRequest
	2, // 3: testpb.TestService.UpdateTest:input_type -> testpb.UpdateTestRequest
	3, // 4: testpb.TestService.CreateTest:output_type -> testpb.CreateTestResponse
	4, // 5: testpb.TestService.UpdateTest:output_type -> testpb.UpdateTestResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_test_proto_init() }
func file_proto_test_proto_init() {
	if File_proto_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_test_proto_rawDesc), len(file_proto_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_test_proto_goTypes,
		DependencyIndexes: file_proto_test_proto_depIdxs,
		MessageInfos:      file_proto_test_proto_msgTypes,
	}.Build()
	File_proto_test_proto = out.File
	file_proto_test_proto_goTypes = nil
	file_proto_test_proto_depIdxs = nil
}
